# Generated by Django 4.1.7 on 2023-03-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(null=True),
        ),
    ]
