# Generated by Django 4.1.7 on 2023-03-13 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_subscribed_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribed',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribed_user', to='apis.userdata'),
        ),
    ]
